### PR TITLE
Making the window height/width and status bar configurable

### PR DESCRIPTION
**Pull request by Garethp**
Making the window height/width configurable, adding in a new toggleable status line, and setting default layout to "better" layout

### CODE REVIEW

**Comment by Garethp** [comment]
@BlackIkeEagle Is this what you were after when I first suggested the more compact layout?

**Comment by BlackIkeEagle** [comment]
Screenshot_20190704_193308

example of the weirdness with width 60

**Comment by BlackIkeEagle** [comment]
removed the width 60 in a followup to have 2 windows wit identical width

Screenshot_20190704_204206

**Comment by BlackIkeEagle** [comment]
Some extras:

add :record_button: glyph for listening status
and make sure the simplified status always prints just one line

**Comment by BlackIkeEagle** [comment]
@Garethp and @Taluu I was a bit triggered by this PR to investigate further and came up with a 'view_preset' where you can choose if you want this new layout, or the previous layout (with the windows re-arranged)

see: #408

**Pull request merged**
