### PR TITLE
Better layout

### PR DESCRIPTION
**Pull request by phatsk**
Following the discussion [here](https://github.com/vim-vdebug/vdebug/issues/360), and seeing as it looks like this may not be maintained by @garethp any longer, I'm opening this PR to hopefully get visibility on the better layout. I've just used Gareth's `better-layout` branch and I definitely like it more than the default in terms of how my space is utilized.

image

### CODE REVIEW

**Comment by BlackIkeEagle** [comment]
@phatsk could you strip this PR down to the relevant parts only please, currently you are dragging in a lot of stuff that is no longer needed to make this layout update work. I would also rather have an update that is not having a fixed layout, but lets you choose how you want your layout to look.

**Comment by phatsk** [comment]
I'll try to do the best that I can to at least merge in current and resolve conflicts, but my vim-fu might not be up to the task of making this configurable. We'll see!

**Comment by Garethp** [comment]
@phatsk You're right that I'm not maintaining this (I don't really use VIM all that often, I just like to muck around now and then for fun), but here's some advice:

You should be able to pare down the PR by looking at the one commit that actually changes the layout to look like this, which you can find [`here`](https://github.com/Garethp/vdebug/commit/30369d5824fb2098733edf47eee0d2205e8cece6). And referring to my initial feature suggestion ticket, there's two main things that need to be configurable to get this working:

 * Being able to set the height for each window
 * The option to allow for the single line status bar

The option bar is the easiest, you throw a boolean value into the default options and then read from it at [`set_status`](https://github.com/Garethp/vdebug/commit/30369d5824fb2098733edf47eee0d2205e8cece6#diff-6414f64bd58ad0be1a6a2b6f2c24c1c7R645) to either set the status bar to text or set it to an icon. The first one should just be a case of adding a `height` and `width` option to windows and setting said height and width in `vimui`.

It looks like adding options shouldn't be too difficult. You add the option in as JSON in the vim plugin [`here`](https://github.com/Garethp/vdebug/blob/master/plugin/vdebug.vim#L80), and then you can simply read from that option with the `opt` module, with one example being in [`session.py`](https://github.com/vim-vdebug/vdebug/blob/master/python3/vdebug/session.py#L164)

**Comment by Garethp** [comment]
Actually, once I wrote that comment it all seemed pretty easy, so I've opened a PR at #402

**Comment by BlackIkeEagle** [comment]
lets favour #402 and close thisone

**Pull request closed without merging**
